### ISSUE TITLE
[Quais] - Fix Broken Unit Tests

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais.js#115]
Breakdown the specific areas in Quais below:

- [ ] JSON RPC signer is gone (removed)
- [ ]

**Comment by robertlincecum** [comment]
Tests that will remain correctly failing due to other issues that need to be fixed:

1)

ERROR 1: "before all" hook for "confirms the contract deployment"
Error: could not coalesce error (error={ "code": -32000, "message": "address is not in scope" }, payload={ "id": 13, "jsonrpc": "2.0", "method": "quai_getCode", "params": [ "0x00550d4412B1e4558E34092b61679DA93D862278", "latest" ] }, code=UNKNOWN_ERROR, version=0.0.1)

Cause: There is a bug in go-quai on the quai_getCode RPC endpoint where if you try to get the code for a correct address, it will incorrectly return out of scope. It seems that when the incoming address is turned to byte form, it changes somehow.

2)

ERROR 2: "before all" hook for "should fetch block by number"
TypeError: Cannot read properties of undefined (reading 'map')

Cause: The block formatter needs to be implemented in quais. Refer to issue 

3)

ERROR 3: should fetch transaction receipt for internal to external tx
TypeError: Cannot read properties of null (reading '0')

Cause: There is a bug in go-quai where retrieving the receipt of a transaction that was supposed to create an ext returns null for the etxs field.

4)

ERROR 158: computes the create address: random-15.7
AssertionError [ERR_ASSERTION]: '0xc06745eB6d4475304EC8Cfe0Edf8B5b20DA94acC' == '0xc8d9fEAf96B8a4C1c965c63dF923a3Aed9Ae4FeB'

Cause: quais needs to replicate go-quai's implementation of the createAddress for contracts. Refer to issue
