### ISSUE TITLE
[Quais] - Enforce camelCase encoding for checksum on RPCs in Quais

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais.js#26]
Requirements:

Change the formatting for checksum address to enforce camelcase formatting.
When a checksum request comes through an RPC, if it is not formatted correctly a failure message should be returned.

**Comment by mibuono** [comment]
We do not want to do any checksum formatting for transactions.  

We want to check the address that we want to send from or to, and throw an error if it is invalid.

**Comment by rileystephens28** [comment]
To be specific here, we do not want to perform any camel case checksum formatting on addresses that were supplied to the SDK by the user. This applies primarily to addresses that are used as inputs for a transactions (`from`, `to`, `txInputs`, `txOutputs`). For all address input fields for a transaction, we should check if they are properly camel case checksummed and if not, we throw an error.

 We **DO** want provide proper camel case checksummed addresses when they are derived from a wallet rather than supplied by the user!
